apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bakery-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/komalumare/bakery-app.git'
    targetRevision: HEAD
    path: chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

